### ISSUE TITLE
BUD-35 Fixes Debt Calculator

### ISSUE THREAD

**Issue by icbryant9** [icbryant9/BudgetBuddy#4]

**Comment by icbryant9** [comment]
Task Description
- Debt Calculator should be completed by the end of this iteration.  Should be able to calculate things like principle and monthly payments.
- A scaffold should be created that allows you to enter information about debt and get quotes.  It should also allow you to save and edit this data

 How to Evaluate
- Go to localhost:3000/calculate_debt
- Log in with either (alice@gmail.com, password) or (bob@gmail.com, password)
- Enter data in the filed and make sure that the works without any errors
- View the index page and make sure you can only see the Quotes of the signed-in user

To evaluate this at a high level just make sure that it works and you get the correct numbers for inputted information.  I used the loan formula to get the desired values and did all computation in the model's file.

**Comment by borstad** [comment]
Closing because it didn't properly close when referenced in pull request.
@icbryant9 if this isn't supposed to be closed, I'll open it back up. Looking at the pull request history it looks like it should be.
